name: CommandObfuscator
main: ch.tekk.commandobfuscator.Main
version: 1.0
api-version: 1.19
author: Tekk
description: A timed teleport plugin.
permissions:
  command-obfuscator.*:
    description: Gives access to all CommandObfuscator permissions
    children:
      command-obfuscator.bypass:
        description: Bypasses command-obfuscator